name: Deploy Serverless App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS SAM
      run: |
        pip install aws-sam-cli

    - name: Deploy using SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --stack-name serverless-order-app --capabilities CAPABILITY_IAM
